Colonna A {.sidebar}
-----------------------------------------------------------------------

### 

#### 

```{r}
renderUI({    
  req(Info_BR())
  pickerInput(
    inputId = "i3B_to_transf", label = "Select a variable (or a group of variables) to transform", multiple = TRUE,
    choices = names(Info_BR())[-1],
    options = c(pkr_opt, `actions-box` = TRUE)
  )
})
```

#### 

```{r}
renderUI({
  req(input$i3B_to_transf)
  
  nvs <- length(c(input$i3B_to_transf))
  if(nvs == 1){
    pickerInput(
      inputId = "i3B_quale_transf",
      label = "Select a transformation (one variable)",
      multiple = TRUE,
      choices = list(`Transform a single variable` = trans_single),
      options = pkr_opt
    )
  }else{
    pickerInput(
      inputId = "i3B_quale_transf",
      label = "Select a transformation (several variables)",
      multiple = TRUE,
      choices = list(
        `Transform a group of variables` = trans_multi),
      options = pkr_opt
    )
  }
})

renderUI({
  req(input$i3B_quale_transf)
  actionButton("i3B_done_trans", "Click when done", icon("paper-plane"), 
               style="color: #fff; background-color: #337ab7; border-color: #2e6da4")
})
```

Colonna wrang {.tabset}
-----------------------------------------------------------------------
### Create a variable to be assigned to $\mathbf{X}_B$

```{r}
var_to_transform_B <- reactive({
  req(input$i3B_quale_transf)
  if(input$i3B_quale_transf %in% trans_single){
    out_data <- Info_BR()[[input$i3B_to_transf]]
  }
  if(input$i3B_quale_transf %in% trans_multi){
    out_data <- Info_BR()[input$i3B_to_transf]
  }
  out_data
})

# 
uiOutput("ui_trans_B")
output$ui_trans_B <- renderUI({
  req(input$i3B_quale_transf)
  req(input$i3B_to_transf)
  if(input$i3B_quale_transf == "Add as it is") {
    u <- add_as_is_UI("id_var_add_as_is_B", input$i3B_to_transf)
  }
  if(input$i3B_quale_transf == "Rename variable") {
    u <- no_trans_UI("id_var_no_trans_B")
  }
  if(input$i3B_quale_transf == "Quantitative to categorical") {
    u <- quant_to_cat_UI("id_var_trans_quant_to_cat_B")
  }
  if(input$i3B_quale_transf == "Recode a factor") {
    u <- cat_to_cat_UI("id_var_trans_cat_to_cat_B")
  }
  if(input$i3B_quale_transf == "Count the number of occurrences") {
    u <- conta_se_vec_UI("id_var_trans_conta_se_B")
  }
  if(input$i3B_quale_transf == "Check if some categories occur row-wise") {
    u <- check_se_vec_UI("id_var_trans_check_se_B")
  }
  if(input$i3B_quale_transf == "Sum row-wise") {
    u <- somma_vec_UI("id_var_trans_somma_B")
  }
  u
})


out_add_as_is_B <- add_as_is_SERVER("id_var_add_as_is_B", var_to_transform_B)
out_no_trans_B <- no_trans_SERVER("id_var_no_trans_B", var_to_transform_B)
out_quant_to_cat_B <- quant_to_cat_SERVER("id_var_trans_quant_to_cat_B", var_to_transform_B)
out_cat_to_cat_B <- cat_to_cat_SERVER("id_var_trans_cat_to_cat_B", var_to_transform_B)
out_conta_se_B <- conta_se_vec_SERVER("id_var_trans_conta_se_B", var_to_transform_B)
out_check_se_B <- check_se_vec_SERVER("id_var_trans_check_se_B", var_to_transform_B)
out_somma_B <- somma_vec_SERVER("id_var_trans_somma_B", var_to_transform_B)


transformed_var_B <- reactive({
  req(input$i3B_quale_transf)
  if(input$i3B_quale_transf == "Add as it is") {
    u <- as_tibble(out_add_as_is_B())
  }
  if(input$i3B_quale_transf == "Rename variable") {
    u <- as_tibble(out_no_trans_B())
  }
  if(input$i3B_quale_transf == "Quantitative to categorical") {
    u <- as_tibble(out_quant_to_cat_B())
  }
  if(input$i3B_quale_transf == "Recode a factor") {
    u <- as_tibble(out_cat_to_cat_B())
  }
  if(input$i3B_quale_transf == "Count the number of occurrences") {
    u <- as_tibble(out_conta_se_B())
  }
  if(input$i3B_quale_transf == "Check if some categories occur row-wise") {
    u <- as_tibble(out_check_se_B())
  }
  if(input$i3B_quale_transf == "Sum row-wise") {
    u <- as_tibble(out_somma_B())
  }
  u
})

# STORAGE VARIABILI TRASFORMATE ---- IMPORTANTISSIMO OGGETTO
X_B <- reactiveVal()

observeEvent(input$i3B_done_trans, {
  X_B(bind_cols(X_B(), transformed_var_B()))
  if(!(names(transformed_var_B()) %in% names(Info_BR()))){
    Info_BR(bind_cols(Info_BR(), transformed_var_B()))
  }
  
  updatePickerInput(session = session, inputId = "i3B_quale_transf", selected = "")
  updatePickerInput(session = session, inputId = "i3B_to_transf", selected = "")
})

```
### See the $\mathbf{X}_B$ data frame
```{r}
DT::renderDT({
  X_B()
})
```


